=== lenkei-mark/AQC53ZxmlGyak/XMLFeladataqc53z/XMLSchemaaqc53z.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Tulajdonosok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Tulajdonos" type="Tulajdonos_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pizzeriak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Pizzeria" type="Pizzeria_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pizzak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Pizza" type="Pizza_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Vevok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Vevo" type="Vevo_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Tulajdonos_Pizzeria_kapcsolok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Tulajdonos_Pizzeria" type="Tulajdonos_Pizzeria_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pizzeria_Pizza_kapcsolok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Pizzeria_Pizza" type="Pizzeria_Pizza_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pizza_Vevo_kapcsolok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Pizza_Vevo" type="Pizza_Vevo_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="Tulajdonos_type">
		<xs:sequence>
			<xs:element name="Nev"></xs:element>
			<xs:element name="Szulido" type="Szulido_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="Tkod" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Pizzeria_type">
		<xs:sequence>
			<xs:element name="Nev"></xs:element>
			<xs:element name="Telefonszam" maxOccurs="unbounded"></xs:element>
			<xs:element name="Cim" type="Cim_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="Pikod" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Pizza_type">
		<xs:sequence>
			<xs:element name="Nev"></xs:element>
			<xs:element name="Ar"></xs:element>
			<xs:element name="Feltet" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="Pkod" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Vevo_type">
		<xs:sequence>
			<xs:element name="Nev"></xs:element>
			<xs:element name="Telefonszam"></xs:element>
			<xs:element name="Cim" type="Cim_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="Vkod" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Tulajdonos_Pizzeria_kapcsolo">
		<xs:attribute name="Tulajdonosref" type="xs:integer" use="required"></xs:attribute>
		<xs:attribute name="Pizzeriaref" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Pizzeria_Pizza_kapcsolo">
		<xs:attribute name="Pizzeriaref" type="xs:integer" use="required"></xs:attribute>
		<xs:attribute name="Pizzaref" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Pizza_Vevo_kapcsolo">
		<xs:attribute name="Pizzaref" type="xs:integer" use="required"></xs:attribute>
		<xs:attribute name="Vevoref" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Cim_type">
		<xs:sequence>
			<xs:element name="Irszam"></xs:element>
			<xs:element name="Varos"></xs:element>
			<xs:element name="Utca"></xs:element>
			<xs:element name="Hazszam"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Szulido_type">
		<xs:sequence>
			<xs:element name="Ev"></xs:element>
			<xs:element name="Honap"></xs:element>
			<xs:element name="Nap"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== lenkei-mark/AQC53ZxmlGyak/XMLFeladataqc53z/DOMParseaqc53z/src/hu/domparse/aqc53z/XMLaqc53z.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaaqc53z.xsd">
	<Tulajdonosok>
	
		<Tulajdonos Tkod="1">
			<Nev>Nagy Béla</Nev>
			<Szulido>
				<Ev>1987</Ev>
				<Honap>03</Honap>
				<Nap>12</Nap>
			</Szulido>
		</Tulajdonos>
		
		<Tulajdonos Tkod="2">
			<Nev>Lőre István</Nev>
			<Szulido>
				<Ev>1967</Ev>
				<Honap>10</Honap>
				<Nap>25</Nap>
			</Szulido>
		</Tulajdonos>
		
		<Tulajdonos Tkod="3">
			<Nev>Kiss Imre</Nev>
			<Szulido>
				<Ev>1980</Ev>
				<Honap>08</Honap>
				<Nap>20</Nap>
			</Szulido>
		</Tulajdonos>
		
	</Tulajdonosok>
	
	<Pizzeriak>
		<Pizzeria Pikod="1">
			<Nev>Italian Stallion</Nev>
			<Telefonszam>012432123</Telefonszam>
			<Cim>
				<Irszam>1256</Irszam>
				<Varos>Budapest</Varos>
				<Utca>Ferencziek útja</Utca>
				<Hazszam>14</Hazszam>
			</Cim>
		</Pizzeria>
		
		<Pizzeria Pikod="2">
			<Nev>New York Style</Nev>
			<Telefonszam>05618478</Telefonszam>
			<Cim>
				<Irszam>3525</Irszam>
				<Varos>Miskolc</Varos>
				<Utca>Széchenyi István út</Utca>
				<Hazszam>26</Hazszam>
			</Cim>
		</Pizzeria>
		
		<Pizzeria Pikod="3">
			<Nev>Lábas</Nev>
			<Telefonszam>035637923</Telefonszam>
			<Cim>
				<Irszam>3540</Irszam>
				<Varos>Alsózsolca</Varos>
				<Utca>Fő út</Utca>
				<Hazszam>6</Hazszam>
			</Cim>
		</Pizzeria>
	</Pizzeriak>
	
	<Pizzak>
		<Pizza Pkod="1">
			<Nev>Margareta</Nev>
			<Ar>1200</Ar>
			<Feltet>Sajt</Feltet>
		</Pizza>
		
		<Pizza Pkod="2">
			<Nev>Sonkás</Nev>
			<Ar>1400</Ar>
			<Feltet>Sajt</Feltet>
			<Feltet>Sonka</Feltet>
		</Pizza>
		
		<Pizza Pkod="3">
			<Nev>Szalámis</Nev>
			<Ar>1400</Ar>
			<Feltet>Sajt</Feltet>
			<Feltet>Szalámi</Feltet>
		</Pizza>
		
		<Pizza Pkod="4">
			<Nev>Sonkás-Kukoricás</Nev>
			<Ar>1600</Ar>
			<Feltet>Sajt</Feltet>
			<Feltet>Sonka</Feltet>
			<Feltet>Kukorica</Feltet>
		</Pizza>
		
		<Pizza Pkod="5">
			<Nev>Lábas Speciál</Nev>
			<Ar>2100</Ar>
			<Feltet>Sajt</Feltet>
			<Feltet>BBQ szósz</Feltet>
			<Feltet>Pulled Pork</Feltet>
			<Feltet>Bacon</Feltet>
		</Pizza>
	</Pizzak>
	
	<Vevok>
		<Vevo Vkod="1">
			<Nev>Nagy Ferenc</Nev>
			<Telefonszam>77895412</Telefonszam>
			<Cim>
				<Irszam>3519</Irszam>
				<Varos>Miskolc</Varos>
				<Utca>Fenyő utca</Utca>
				<Hazszam>23</Hazszam>
			</Cim>
		</Vevo>
		
		<Vevo Vkod="2">
			<Nev>Novák Balázs</Nev>
			<Telefonszam>078954412</Telefonszam>
			<Cim>
				<Irszam>1149</Irszam>
				<Varos>Budapest</Varos>
				<Utca>Vezér utca</Utca>
				<Hazszam>149</Hazszam>
			</Cim>
		</Vevo>
		
		<Vevo Vkod="3">
			<Nev>Trab Antal</Nev>
			<Telefonszam>012258</Telefonszam>
			<Cim>
				<Irszam>3530</Irszam>
				<Varos>Miskolc</Varos>
				<Utca>Pattantyús utca</Utca>
				<Hazszam>14</Hazszam>
			</Cim>
		</Vevo>
	</Vevok>
	
	<Tulajdonos_Pizzeria_kapcsolok>
		<Tulajdonos_Pizzeria Tulajdonosref="1" Pizzeriaref="1"></Tulajdonos_Pizzeria>
		<Tulajdonos_Pizzeria Tulajdonosref="2" Pizzeriaref="2"></Tulajdonos_Pizzeria>
		<Tulajdonos_Pizzeria Tulajdonosref="2" Pizzeriaref="3"></Tulajdonos_Pizzeria>
	</Tulajdonos_Pizzeria_kapcsolok>
	
	<Pizzeria_Pizza_kapcsolok>
		<Pizzeria_Pizza Pizzeriaref="1" Pizzaref="1"></Pizzeria_Pizza>
		<Pizzeria_Pizza Pizzeriaref="1" Pizzaref="3"></Pizzeria_Pizza>
		<Pizzeria_Pizza Pizzeriaref="2" Pizzaref="2"></Pizzeria_Pizza>
		<Pizzeria_Pizza Pizzeriaref="2" Pizzaref="4"></Pizzeria_Pizza>
		<Pizzeria_Pizza Pizzeriaref="3" Pizzaref="5"></Pizzeria_Pizza>
	</Pizzeria_Pizza_kapcsolok>
	
	<Pizza_Vevo_kapcsolok>
		<Pizza_Vevo Vevoref="1" Pizzaref="2"></Pizza_Vevo>
		<Pizza_Vevo Vevoref="2" Pizzaref="4"></Pizza_Vevo>
		<Pizza_Vevo Vevoref="3" Pizzaref="5"></Pizza_Vevo>
	</Pizza_Vevo_kapcsolok>
	
	
</model>
